groups:
  - name: mlops_alerts
    rules:
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is above 1 second for 2 minutes"

      - alert: HighErrorRate
        expr: rate(api_requests_total{status=~"5.."}[5m]) / rate(api_requests_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 1 minute"

      - alert: ModelPredictionFailure
        expr: increase(model_predictions_total[5m]) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "No model predictions in 5 minutes"
          description: "Model {{ $labels.model_name }} has not made any predictions"

      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for 2 minutes"

      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% for 1 minute"

      - alert: APIDown
        expr: up{job="mlops-api"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MLOps API is down"
          description: "The MLOps API service is not responding"