# Grafana datasource provisioning for Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "60s"
      defaultRegion: "default"
      customQueryParameters: ""
      manageAlerts: true
      alertmanagerUid: "alertmanager"
    secureJsonData: {}

  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      implementation: "prometheus"
      handleGrafanaManagedAlerts: true
    uid: "alertmanager"