name: Automated Model Retraining

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      models:
        description: 'Comma-separated list of models to retrain (iris,house_price,sentiment,churn,image)'
        required: false
        default: 'all'

jobs:
  retrain-models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create fresh datasets
      run: python data/create_datasets.py

    - name: Retrain models
      run: |
        if [ "${{ github.event.inputs.models }}" = "all" ] || [ -z "${{ github.event.inputs.models }}" ]; then
          python scripts/train_all_models.py
        else
          echo "Retraining specific models: ${{ github.event.inputs.models }}"
          # Add logic to retrain specific models
        fi

    - name: Validate new models
      run: python tests/test_model_performance.py

    - name: Compare model performance
      run: python scripts/compare_model_performance.py

    - name: Create PR with new models
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🤖 Automated model retraining"
        title: "Automated Model Retraining - $(date +'%Y-%m-%d')"
        body: |
          ## Automated Model Retraining

          This PR contains updated models from automated retraining.

          ### Changes
          - Retrained models with fresh data
          - Updated model artifacts
          - Performance validation completed

          ### Next Steps
          - [ ] Review model performance metrics
          - [ ] Approve and merge if performance is satisfactory
          - [ ] Deploy updated models
        branch: automated-retraining-$(date +'%Y%m%d')
        delete-branch: true