name: Model Monitoring and Alerts

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  monitor-models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check model performance
      run: python monitoring/check_model_performance.py

    - name: Check data drift
      run: python monitoring/check_data_drift.py

    - name: Generate monitoring report
      run: python monitoring/generate_report.py

    - name: Upload monitoring artifacts
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-report-${{ github.run_number }}
        path: monitoring/reports/

    - name: Create issue for alerts
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Model Monitoring Alert - ' + new Date().toISOString().split('T')[0],
            body: `## Model Monitoring Alert

            The automated monitoring job has detected issues that require attention.

            **Run Details:**
            - Workflow: ${context.workflow}
            - Run Number: ${context.runNumber}
            - Commit: ${context.sha}

            **Recommended Actions:**
            1. Check the workflow logs for details
            2. Review model performance metrics
            3. Investigate data drift patterns
            4. Consider model retraining if necessary

            This issue was automatically created by the monitoring workflow.`,
            labels: ['monitoring', 'alert', 'automated']
          })